version: '3'
services:
  mysql:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "tradeservice"
      MYSQL_USER: "tradeservice"
      MYSQL_PASSWORD: "password"
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
#  zookeeper:
#    image: wurstmeister/zookeeper:latest
#    ports:
#      - "2181:2181"
#  kafka:
#    image: wurstmeister/kafka:latest
#    ports:
#      - "9092:9092"
#    environment:
#      KAFKA_LISTENERS: PLAINTEXT://:9092
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#      KAFKA_CREATE_TOPICS: "TradeCreated:1:1,TradeSettled:1:1,WalletBalanceDeducted:1:1,WalletBalanceAdded:1:1"
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock